#!/usr/bin/env bash
#servers are the piece of software generating and serving HTML pages
sudo apt-get update

sudo apt-get install nginx
sudo su
echo "Hello World" >/var/www/html/index.nginx-debian.html
sudo service nginx restart
