#!/usr/bin/env bash
#Install nginx on your web-01 server
#Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo su
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
