#!/usr/bin/env bash
#Install nginx on your web-02 server

sudo su
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a \\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404_error.html
sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
