#!/usr/bin/env bash
# a Bash script that displays Best School 10 times
#but for the 9th iteration, displays Best School and then Hi
conpteur=10

while [ $conpteur -ge 1 ]
do
  if [[ "$conpteur" == '2' ]]; then
    echo "Hi"
  else
    echo "Best School"
  fi
  ((conpteur--))
done
