#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 and:
conpteur=1
while [ $conpteur -lt 21 ]
do
  echo $conpteur
    case "$conpteur" in
      4) echo "bad luck from China";;
      9) echo "bad luck from Japan";;
      17) echo "bad luck from Italy";;
    esac
    ((conpteur++))

done
