#!/usr/bin/env bash
#script that gives you information about the holbertonschool file
File="holbertonschool"

if [ -e "$File" ]
then
	echo "$File file exists"
	if [ ! -s "$File" ]
	then
		echo "$File file is empty"
	else
		echo "$File file is not empty"
	fi
	if [ -f "$File" ]
	then
		echo "$File is a regular file"
	fi
else
	echo "$File file does not exist"
fi
