#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.old
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.old
cp -f ~/hosts.old /etc/hosts
