#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements.
sudo su
cp /etc/hosts ~/hosts.old
sed -i 's/.*localhost/127.0.0.2 localhost/g' /etc/hosts
sed -i 's/.*facebook.com//g' /etc/hosts
sed -i '1 a 8.8.8.8 facebook.com' /etc/hosts
