#!/usr/bin/env bash
#a Bash script that configures the container to fit the above requirements
sudo su
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill apache2
chmod 004 /etc/nginx/nginx.conf
service nginx stop
sudo -u nginx service nginx start
