#!/usr/bin/env bash
#a Bash script that configures the container to fit the above requirements
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo pkill apache2
chmod 004 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
