#!/usr/bin/env bash

#Your SSH client configuration must be configured to use the private key ~/.ssh/holberton
#Your SSH client configuration must be configured to refuse to authenticate using a password

Host 35.196.9.127
  User ubuntu
  IdentityFile ~/.ssh/holberton
  IdentitiesOnly yes
  PasswordAuthentication no
